### ISSUE TITLE
Really interested in this but can't get it to work

### ISSUE THREAD

**Issue by tomwardrop** [artlasovsky/fyrlykt#2]
Hi,

Do you have a binary for download? I've installed Go and lots of other things to try and get this to build but i keep getting errors.

In file included from ./bitmap/../base/str_io_c.h:2,
                 from ./bitmap/goBitmap.h:17,
                 from ..\..\..\..\go\pkg\mod\github.com\go-vgo\robotgo@v0.0.0-20200418182153-af1d0d2d00a1\robotgo.go:45:
./bitmap/../base/zlib_util_c.h:2:10: fatal error: zlib.h: No such file or directory
    2 | #include <zlib.h>

is the latest now

Thanks

**Comment by johanlef** [comment]
Mac or PC? @tomwardrop I have a Mac binary, if you are interested…

**Comment by artlasovsky** [comment]
Hey! 
Sorry that not answer earlier.

I have updated the app. Cleanup the code and update electron configuration. Now it's working both on macOS and Windows (I have tested it on macOS BigSur and Windows 10).
